common:
  env:
    APP_HOST: "https://substrate-tip-bot.parity-stg.parity.io"
    DATABASE_NAME: "substrate-tip-bot"
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/target: traefik-external.parity-stg.parity.io.
    rules:
    - host: substrate-tip-bot.parity-stg.parity.io
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: substrate-tip-bot
              port:
                name: http
    tls:
    - hosts:
      - substrate-tip-bot.parity-stg.parity.io
      secretName: substrate-tip-bot.parity-stg.parity.io
